FROM ubuntu
RUN touch file1 file2 aws
HELLO THIS IS EXTRA DATA WE ARE ADDING TO THIS FILE
ADDING SOME MORE CONTENT
THIS IS JENKINS CLASS, THANKS FOR JOINING
475683973023@#$%^&*()
ADDING SOME NEW CONTENT BY DEV-4
